ARG ARTIFACT_JAR_NAME="deposit-0.0.1-SNAPSHOT.jar"
ARG JAR_NAME="deposit-demo.jar"
ARG BUILD_DIR="/app"
ARG EXPOSED_PORT=8088
ARG JAVA_OPTS=""

FROM maven:3.9.7-eclipse-temurin-21 AS build
ARG BUILD_DIR
WORKDIR ${BUILD_DIR}
COPY pom.xml .
COPY src ./src
RUN mvn clean package

FROM eclipse-temurin:21
ARG ARTIFACT_JAR_NAME
ARG JAR_NAME
ARG BUILD_DIR
ARG EXPOSED_PORT
ARG JAVA_OPTS
ENV APP_EXECUTABLE=${JAR_NAME} JAVA_OPTIONS=${JAVA_OPTS}
WORKDIR /opt/${BUILD_DIR}
COPY --from=build ${BUILD_DIR}/target/${ARTIFACT_JAR_NAME} ./${JAR_NAME}
EXPOSE ${EXPOSED_PORT}
ENTRYPOINT java ${JAVA_OPTIONS} -jar ${APP_EXECUTABLE}