server.port: 8088

logging:
  level:
    org:
      hibernate:
        SQL: "DEBUG"
        orm:
          jdbc:
            bind: "TRACE"

spring:
  security:
    user:
      name: demo
      password: demo
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console.enabled: true
    path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    configprops:
      show-values: "ALWAYS"
    env:
      show-values: "ALWAYS"
    shutdown:
      enabled: true
  jmx:
    exposure:
      include: "health,info"

